### ISSUE TITLE
英才帝国百科全书 | SocialZxy's Blog

### ISSUE THREAD

**Issue by SocialZxy** [SocialZxy/SocialZxy.github.io#1]
https://socialzxy.github.io/2020/03/27/%E8%8B%B1%E6%89%8D%E5%B8%9D%E5%9B%BD%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6/#%E8%96%AF%E7%89%87%E8%84%9A 

 关于某资本主义屑校的一些屁事——来自一个即将离开的年级倒一的科普

**Comment by RPChe-6626** [comment]
C█Y在此

**Comment by SocialZxy** [comment]
> @RPChe-6626
> C█Y在此

C█Y nb
